name: "Wynik przeglądu aplikacji - rekomendacja"
description: "Zgłoś rekomendację"
labels: ["NFR", "recommendation"]
body:
   - type: markdown
       attributes:
         value: "Wprowadź treść issue"
   - type: textarea
       attributes:
          label: "Description"
