
name: Wniosek o obniżenie progu SLO
description: Template do zgłaszania wniosku o obniżenie progu SLO
title: "[Wniosek] Obniżenie progu SLO dla aplikacji"
labels: ["SLO"]
assignees:
  - kampiech

body:
  - type: markdown
    attributes:
      value: |
        # Wniosek o obniżenie progu SLO

  - type: input
    id: name
    attributes:
      label: "Nazwa usługi"
    validations:
      required: true

  - type: textarea
    id: summary
    attributes:
      label: "Podsumowanie analizy niespełnienia SLO"
      description: "Opisz krótko, dlaczego aplikacja nie spełnia obecnego progu SLO oraz dlaczego nie jest możliwe lub sensowne jego osiągnięcie."
    validations:
      required: true

  - type: input
    id: new_threshold
    attributes:
      label: "Propozycja nowego progu"
    validations:
      required: true

  - type: input
    id: duration
    attributes:
      label: "Czas obowiązywania obniżonego progu"
    validations:
      required: true
      
  - type: textarea
    id: additional_info
    attributes:
      label: "Dodatkowe informacje"
