
name: Wniosek o Obniżenie Thresholdu SLO
description: Template do zgłaszania wniosku o obniżenie progu SLO
title: "[Wniosek] Obniżenie Thresholdu SLO dla aplikacji"
labels: ["SLO"]
assignees:
  - newpma
  - kampiech
  - michalsgp
  - gazdzinskak

body:
  - type: markdown
    attributes:
      value: |
        # Wniosek o Obniżenie Thresholdu SLO

  - type: input
    id: name
    attributes:
      label: "Nazwa usługi"
    validations:
      required: true

  - type: textarea
    id: summary
    attributes:
      label: "Podsumowanie analizy niespełnienia SLO"
      description: "Opisz krótko, dlaczego aplikacja nie spełnia obecnego progu SLO"
    validations:
      required: true

  - type: input
    id: new_threshold
    attributes:
      label: "Propozycja nowego thresholdu"
    validations:
      required: true

  - type: input
    id: duration
    attributes:
      label: "Czas obowiązywania obniżonego thresholdu"
    validations:
      required: true
      
  - type: textarea
    id: additional_info
    attributes:
      label: "Dodatkowe informacje"
